# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Voice of Students
subtitle: By the BINJ News club
name: Voice of Students  # default author name
email: svib-news@outlook.com
locale: en-US
logo: /assets/images/logo.png
description: >-
  Voice of Students news is designed to give students a voice in the school,
  offering unique content unprovided on the official platform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://svib-news.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: minima
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark
plugins:
  - jekyll-feed
  - jekyll-archives

include:
  - _pages
  - Issues
  - Articles

defaults:
  # all posts and pages
  - scope:
      path: ""
    values:
      author: SVIB News
      author_profile: true
      layout: single
  # posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      permalink: /:categories/:title/
      breadcrumbs: true
  # pages
  - scope:
      path: ""
      type: pages
    values:
      author_profile: false
  # Issues only
  - scope:
      path: Issues
      type: posts
    values:
      layout: issue
      excerpt: ""
      read_time: false
  # Articles only
  - scope:
      path: Articles
      type: posts
    values: {}

footer_scripts:
  - /assets/js/captions.js

jekyll-archives:
  enabled:
    - categories
  permalinks:
    category: '/:name/'
  layout: jekyll-archive

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
